// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyncChain.API.Data;

#nullable disable

namespace SyncChain.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SyncChain.API.Models.AuditLog", b =>
                {
                    b.Property<long>("MaAudit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("DuLieuSau")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DuLieuTruoc")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LoaiDoiTuong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MaDoiTuong")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("integer");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TrangThaiKetQua")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaAudit");

                    b.HasIndex("LoaiDoiTuong", "MaDoiTuong", "ThoiGian");
                    b.HasIndex("HanhDong", "ThoiGian");
                    b.HasIndex("MaNguoiDung", "ThoiGian");
                    b.HasIndex("TraceId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("SyncChain.API.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("SyncChain.API.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaDonHang");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("SyncChain.API.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("SyncChain.API.Models.PhanQuyen", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaVaiTro");

                    b.ToTable("PhanQuyen");
                });

            modelBuilder.Entity("SyncChain.API.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinhAnhUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MucTonThap")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaSanPham");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("SyncChain.API.Models.LichSuVanChuyen", b =>
                {
                    b.Property<long>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("integer");

                    b.Property<int>("MaVanChuyen")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TrangThaiCu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TrangThaiMoi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("MaLichSu");
                    b.HasIndex("MaVanChuyen");
                    b.ToTable("LichSuVanChuyen");
                });

            modelBuilder.Entity("SyncChain.API.Models.VanChuyen", b =>
                {
                    b.Property<int>("MaVanChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<int>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("DonViVanChuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("integer");

                    b.Property<string>("MaVanDon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayGiaoDuKien")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayGiaoThucTe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PhiVanChuyen")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TrangThaiGiaoHang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("MaVanChuyen");
                    b.HasIndex("MaDonHang").IsUnique();
                    b.HasIndex("MaVanDon")
                        .IsUnique()
                        .HasFilter("\"MaVanDon\" IS NOT NULL");

                    b.ToTable("VanChuyen", t =>
                        t.HasCheckConstraint(
                            "CK_VanChuyen_PhiVanChuyen_NonNegative",
                            "\"PhiVanChuyen\" >= 0"));
                });

            modelBuilder.Entity("SyncChain.API.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("SyncChain.API.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHang")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SyncChain.API.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("SyncChain.API.Models.LichSuVanChuyen", b =>
                {
                    b.HasOne("SyncChain.API.Models.VanChuyen", "VanChuyen")
                        .WithMany("LichSu")
                        .HasForeignKey("MaVanChuyen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VanChuyen");
                });

            modelBuilder.Entity("SyncChain.API.Models.VanChuyen", b =>
                {
                    b.HasOne("SyncChain.API.Models.DonHang", "DonHang")
                        .WithOne("VanChuyen")
                        .HasForeignKey("SyncChain.API.Models.VanChuyen", "MaDonHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");
                    b.Navigation("LichSu");
                });

            modelBuilder.Entity("SyncChain.API.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHang");
                    b.Navigation("VanChuyen");
                });
#pragma warning restore 612, 618
        }
    }
}
